import { NextResponse } from "next/server";
import { checkRateLimit, sanitize, callGroq, extractJSON } from "@/lib/groq";
const SYS = `You are a Fiverr keyword expert. Find best 2026 keywords. Return ONLY valid JSON no markdown:
{"niche":"...","primaryKeyword":"...","keywords":[{"keyword":"...","searchVolume":"<high|medium|low>","competition":"<high|medium|low>","opportunity":"<high|medium|low>","type":"<primary|secondary|longtail|lsi>","suggestedUse":"<title|tag|description|all>"},{"keyword":"...","searchVolume":"<high|medium|low>","competition":"<high|medium|low>","opportunity":"<high|medium|low>","type":"<primary|secondary|longtail|lsi>","suggestedUse":"<title|tag|description|all>"},{"keyword":"...","searchVolume":"<high|medium|low>","competition":"<high|medium|low>","opportunity":"<high|medium|low>","type":"<primary|secondary|longtail|lsi>","suggestedUse":"<title|tag|description|all>"},{"keyword":"...","searchVolume":"<high|medium|low>","competition":"<high|medium|low>","opportunity":"<high|medium|low>","type":"<primary|secondary|longtail|lsi>","suggestedUse":"<title|tag|description|all>"},{"keyword":"...","searchVolume":"<high|medium|low>","competition":"<high|medium|low>","opportunity":"<high|medium|low>","type":"<primary|secondary|longtail|lsi>","suggestedUse":"<title|tag|description|all>"},{"keyword":"...","searchVolume":"<high|medium|low>","competition":"<high|medium|low>","opportunity":"<high|medium|low>","type":"<primary|secondary|longtail|lsi>","suggestedUse":"<title|tag|description|all>"},{"keyword":"...","searchVolume":"<high|medium|low>","competition":"<high|medium|low>","opportunity":"<high|medium|low>","type":"<primary|secondary|longtail|lsi>","suggestedUse":"<title|tag|description|all>"},{"keyword":"...","searchVolume":"<high|medium|low>","competition":"<high|medium|low>","opportunity":"<high|medium|low>","type":"<primary|secondary|longtail|lsi>","suggestedUse":"<title|tag|description|all>"},{"keyword":"...","searchVolume":"<high|medium|low>","competition":"<high|medium|low>","opportunity":"<high|medium|low>","type":"<primary|secondary|longtail|lsi>","suggestedUse":"<title|tag|description|all>"},{"keyword":"...","searchVolume":"<high|medium|low>","competition":"<high|medium|low>","opportunity":"<high|medium|low>","type":"<primary|secondary|longtail|lsi>","suggestedUse":"<title|tag|description|all>"}],"suggestedTitle":"...","suggestedTags":["...","...","...","...","..."],"trendInsight":"...","nicheOpportunity":"...","avoidKeywords":["...","..."],"seasonalTips":"..."}`;
export async function POST(req) {
  const ip = req.headers.get("x-forwarded-for")?.split(",")[0] || "unknown";
  const rl = checkRateLimit(ip);
  if (!rl.ok) return NextResponse.json({ error: `Rate limit. Wait ${rl.wait}s.` }, { status: 429 });
  const { niche, currentTitle, targetAudience } = await req.json().catch(() => ({}));
  if (!niche || niche.trim().length < 3) return NextResponse.json({ error: "Provide a niche." }, { status: 400 });
  try {
    const text = await callGroq({ sys: SYS, user: `Find Fiverr keywords 2026, return JSON only.\nNICHE: ${sanitize(niche,200)}\nTITLE: ${sanitize(currentTitle||"None",200)}\nAUDIENCE: ${sanitize(targetAudience||"General",200)}` });
    return NextResponse.json({ success: true, result: extractJSON(text) });
  } catch (err) { return NextResponse.json({ error: err.message }, { status: 500 }); }
}
